services:
  accounts:
    image: "viv21094/accounts:s4"
    container_name: accounts-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - viv21094
  loans:
    image: "viv21094/loans:s4"
    container_name: loans-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - viv21094
  cards:
    image: "viv21094/cards:s4"
    container_name: cards-ms
    ports:
      - "9001:9001"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - viv21094
networks:
  viv21094:
    driver: "bridge"